### ISSUE TITLE
OrchestratorConfig definition does not match in docs/src/content/docs/general/quickstart.md  OrchestratorConfig in src/types/index.ts

### ISSUE THREAD

**Issue by sammpath** [awslabs/multi-agent-orchestrator#1]
### Expected Behaviour

`npx ts-node quickstart.ts` runs without error

### Current Behaviour

```
$ npx ts-node quickstart.ts
/home/cloudshell-user/.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/src/index.ts:859
    return new TSError(diagnosticText, diagnosticCodes, diagnostics);
           ^
TSError: ⨯ Unable to compile TypeScript:
quickstart.ts:5:10 - error TS2304: Cannot find name 'logAgentConversation'.
```

### Code snippet

```python
npx ts-node quickstart.ts
```

### Possible Solution

Match names.

### Steps to Reproduce

`npx ts-node quickstart.ts`

**Comment by cornelcroi** [comment]
Thank you for reporting this issue. 

The problem was the outdated `Quickstart` documentation section.

We've identified the problem and updated the quickstart documentation with the correct code. 

Please revisit the quickstart documentation and use the updated code sample and let us know.
Thank you.

**Comment by sammpath** [comment]
Fixed.
