### ISSUE TITLE
Feature request: Add support for GoLang

### ISSUE THREAD

**Issue by D-sense** [awslabs/multi-agent-orchestrator#122]
### Use case

Ability to create an agent in Golang and add it to the orchestrator

### Solution/User Experience

Support for GoLang

### Alternative solutions

```markdown
none
```

**Comment by cornelcroi** [comment]
Thank you for your suggestion regarding additional language support. At present, we are focusing our resources on maintaining and improving support for TypeScript and Python, as these are the most commonly used languages in LLM applications. While we appreciate your proposal, we currently don't have the bandwidth to expand our language offerings due to maintenance requirements.
We'll keep your suggestion in mind for future consideration.
