### ISSUE TITLE
Feature request: Classifier with Amazon Nova Pro

### ISSUE THREAD

**Issue by quangchuamz** [awslabs/multi-agent-orchestrator#143]
### Use case

I'm trying to apply [amazon nova pro model ](amazon.nova-pro-v1:0) for classifier but facing the problem
```shell
ValidationException: This model doesn't support the toolConfig.toolChoice.tool field. Remove toolConfig.toolChoice.tool and try again.
```

### Solution/User Experience

add one classifier for amazon nova pro to suppport

**Comment by brnaba-aws** [comment]
Hi @quangchuamz ,
Thanks for reporting this. We have already added support for models that don't actually support toolChoice (not only Amazon Nova models). This is already [fixed in the current repo](https://github.com/awslabs/multi-agent-orchestrator/blob/36c193a8e446005bb6ecdbf80237774d36ee559d/python/src/multi_agent_orchestrator/classifiers/bedrock_classifier.py#L85) but not release yet. 
You can follow those steps if you want to get moving with Amazon Nova as a classifier:
https://github.com/awslabs/multi-agent-orchestrator/tree/main/python#building-locally

Once we release a new version I'll close this.
Thanks,
Anthony
